version: "1.0"
info:
  model: int-scaffold
packages:
- name: Man_KMAT_Feb7_ExtGITProject
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: WmSalesforceProvider
  version: 10.7.0.0.53
services:
- serviceName: project.man_kmat_feb7_extgit.integrations:Feb10_eGit_ListCRMAccounts
  packages:
  - name: Man_KMAT_Feb7_ExtGITProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.man_kmat_feb7_extgit.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:Cust_KMAT_eGIT
  packages:
  - name: Man_KMAT_Feb7_ExtGITProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
configurationVariables:
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.sessionExpiry
  : "14"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.hostnameVerifier
  : org.apache.http.conn.ssl.NoopHostnameVerifier
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cr.authSchemeType
  : none
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cr.preemptiveAuthEnabled
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.readTimeout
  : "180000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.poolable
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.pr.serverRedirectMax
  : "5"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cr.username
  : dillipkumar.palai@softwareag.com
  ? iscloudstreamsconnectorservice.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:Cust_KMAT_eGIT.connectionAlias
  : project.man_kmat_feb7_extgit.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:Feb7_2_SF_Basic_eGIT_KMAT
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.pr.followServerRedirects
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.rh.requestHeaderNames
  : "Content-Type,SOAPAction"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cr.password
  : "{AES}jBLz2gYx6gF45VYUkhfvJAPTM2hLyRkBm4bFmGpNb/A+yULNKm00UzrKw70pXsPV"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.pr.useChunking
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.providerUrl
  : https://login.salesforce.com/services/Soap/u/53.0
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.pr.useExpectCont
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.pr.allowCircularRedirects
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.pr.httpContentCharSet
  : ISO-8859-1
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.pr.userAgent
  : Cloudstreams
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.retryCount
  : "3"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.pr.protocolVersion
  : HTTP/1.1
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.timeoutType
  : fixed
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.rh.requestHeaderValues
  : "text/xml,login"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.poolIncrementSize
  : "1"
  ? iscloudstreamsconnectorservice.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:Cust_KMAT_eGIT.virtualServiceName
  : WmCloudStreams.SoapVS
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.connectTimeout
  : "180000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb10_SF_Basic_DAF_ConnA.cn.retryIfRequestSentOk
  : "true"
