version: "1.0"
info:
  model: int-scaffold
packages:
- name: Man_KMAT_Feb7_ExtGITProject
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: WmSalesforceProvider
  version: 10.7.0.0.53
services:
- serviceName: project.man_kmat_feb7_extgit.integrations:Feb10_eGit_ListCRMAccounts
  packages:
  - name: Man_KMAT_Feb7_ExtGITProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.man_kmat_feb7_extgit.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:Cust_KMAT_eGIT
  packages:
  - name: Man_KMAT_Feb7_ExtGITProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
configurationVariables:
  ? iscloudstreamsconnectorservice.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:Cust_KMAT_eGIT.connectionAlias
  : project.man_kmat_feb7_extgit.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:Feb7_2_SF_Basic_eGIT_KMAT
  ? iscloudstreamsconnectorservice.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:Cust_KMAT_eGIT.virtualServiceName
  : WmCloudStreams.SoapVS
