version: "1.0"
info:
  model: int-scaffold
packages:
- name: Man_KMAT_Feb7_ExtGITProject
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: WmSalesforceProvider
services:
- serviceName: project.man_kmat_feb7_extgit.integrations:KMAT_eGITtest_1
  packages:
  - name: Man_KMAT_Feb7_ExtGITProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.man_kmat_feb7_extgit.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:Cust_KMAT_eGIT
  packages:
  - name: Man_KMAT_Feb7_ExtGITProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
configurationVariables:
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cr.preemptiveAuthEnabled
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.pr.protocolVersion
  : HTTP/1.1
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.rh.requestHeaderNames
  : "Content-Type,SOAPAction"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.pr.serverRedirectMax
  : "5"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.poolable
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cr.password
  : "{AES}jBLz2gYx6gF45VYUkhfvJAPTM2hLyRkBm4bFmGpNb/A+yULNKm00UzrKw70pXsPV"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.readTimeout
  : "180000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.connectTimeout
  : "180000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cr.authSchemeType
  : none
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.pr.userAgent
  : Cloudstreams
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.readTimeout
  : "180000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cr.password
  : "{AES}jBLz2gYx6gF45VYUkhfvJAPTM2hLyRkBm4bFmGpNb/A+yULNKm00UzrKw70pXsPV"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.providerUrl
  : https://login.salesforce.com/services/Soap/u/53.0
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.pr.allowCircularRedirects
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cr.username
  : dillipkumar.palai@softwareag.com
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.tcpNoDelay
  : "false"
  ? iscloudstreamsconnectorservice.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:Cust_KMAT_eGIT.connectionAlias
  : project.man_kmat_feb7_extgit.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:Feb7_2_SF_Basic_eGIT_KMAT
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.rh.requestHeaderValues
  : "text/xml,login"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.poolable
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.hostnameVerifier
  : org.apache.http.conn.ssl.NoopHostnameVerifier
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cr.username
  : dillipkumar.palai@softwareag.com
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.providerUrl
  : https://login.salesforce.com/services/Soap/u/53.0
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.sessionExpiry
  : "14"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.timeoutType
  : fixed
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.connectTimeout
  : "180000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cr.authSchemeType
  : none
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.timeoutType
  : fixed
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.pr.httpContentCharSet
  : ISO-8859-1
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.retryCount
  : "3"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.pr.userAgent
  : Cloudstreams
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.pr.useExpectCont
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.pr.protocolVersion
  : HTTP/1.1
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.pr.followServerRedirects
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.pr.serverRedirectMax
  : "5"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.rh.requestHeaderNames
  : "Content-Type,SOAPAction"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.pr.httpContentCharSet
  : ISO-8859-1
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.pr.allowCircularRedirects
  : "true"
  ? iscloudstreamsconnectorservice.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:Cust_KMAT_eGIT.virtualServiceName
  : WmCloudStreams.SoapVS
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cr.preemptiveAuthEnabled
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.retryCount
  : "3"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.pr.followServerRedirects
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.rh.requestHeaderValues
  : "text/xml,login"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.pr.useChunking
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.sessionExpiry
  : "14"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_SF_Basic_DAF_eGIT.pr.useExpectCont
  : "false"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..man_kmat_feb7_extgit..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb7_2_SF_Basic_eGIT_KMAT.pr.useChunking
  : "false"
